In [84]:
import h5py
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

import keras
import numpy as np
import pandas as pd
from keras.models import Sequential,load_model
from keras.layers import Conv2D, MaxPooling2D, LSTM, Dense, Dropout, Flatten, BatchNormalization
from keras.layers.core import Permute, Reshape
from keras.callbacks import ReduceLROnPlateau
from keras.callbacks import EarlyStopping, ModelCheckpoint
from keras.regularizers import Regularizer
from keras import regularizers
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
from keras.utils import to_categorical

%matplotlib inline  

### Opening Face Points

In [11]:
FILENAME = 'features_points.h5'
h5f = h5py.File(FILENAME,'r')

for key in h5f.keys():
    print(key) #Names of the groups in HDF5 file.
x = h5f['points'][:]

points


In [12]:
x.shape

(614, 25, 68, 2)

### Getting targets in System

In [13]:
targets = pd.read_csv('merged_labels.csv')
targets.head()


SessionID  Session      Type  Merged Arousal  Merged Dominance  \
0  S001-001-l000        1  Laughter               1                 1   
1  S001-001-l001        1  Laughter               1                 1   
2  S001-001-l002        1  Laughter               2                 2   
3  S001-003-l000        3  Laughter               1                 1   
4  S001-003-l001        3  Laughter               1                 2   

  Merged Emotion  
0          Happy  
1          Happy  
2          Happy  
3  Schadenfreude  
4  Schadenfreude

In [27]:
y = targets['Merged Arousal']
y1 = targets['Merged Dominance']
y2 = targets['Merged Emotion']

In [28]:
def create_graph_arousal_dominance():
    
    model.add(BatchNormalization(input_shape=(WINDOW_SIZE,feat_dim)))
    model.add(LSTM(num_feat_map, 
                   return_sequences=True))
    model.add(BatchNormalization())
    model.add(LSTM(num_feat_map, return_sequences=False))
    model.add(Dropout(0.5))
    model.add(Dense(1,activation='linear'))
    
    model.summary()
    

# Simple LSTM Model Arousal

In [42]:
WINDOW_SIZE = 25
num_feat_map = 16
feat_dim = 136

In [43]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

x_train = x_train.reshape((491,25,-1))
x_test = x_test.reshape((123,25,-1))

model = Sequential()

create_graph_arousal_dominance()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
batch_normalization_11 (Batc (None, 25, 136)           544       
_________________________________________________________________
lstm_11 (LSTM)               (None, 25, 32)            21632     
_________________________________________________________________
batch_normalization_12 (Batc (None, 25, 32)            128       
_________________________________________________________________
lstm_12 (LSTM)               (None, 32)                8320      
_________________________________________________________________
dropout_6 (Dropout)          (None, 32)                0         
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 33        
Total params: 30,657
Trainable params: 30,321
Non-trainable params: 336
_________________________________________________________________


In [44]:
epochs = 50
batch_size=32

#earlystop = EarlyStopping(monitor='val_loss', min_delta=0, patience=10, verbose=1, mode='auto')
#filepath="weights_best_arousal.hdf5"
#checkpoint = ModelCheckpoint(filepath, monitor='val_loss', verbose=1, save_best_only=True, mode='min')

model.compile(loss=keras.losses.mean_squared_error,
              optimizer='adam',
              metrics=['mse'])

model.fit(x_train, y_train,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1,
          shuffle=True,
          validation_data=(x_test, y_test))

Train on 491 samples, validate on 123 samples
Epoch 1/100
491/491 [==============================] - 6s - loss: 4.0999 - mean_squared_error: 4.0999 - val_loss: 5.6497 - val_mean_squared_error: 5.6497
Epoch 2/100
491/491 [==============================] - 1s - loss: 2.3022 - mean_squared_error: 2.3022 - val_loss: 3.2572 - val_mean_squared_error: 3.2572
Epoch 3/100
491/491 [==============================] - 1s - loss: 1.5412 - mean_squared_error: 1.5412 - val_loss: 2.1329 - val_mean_squared_error: 2.1329
Epoch 4/100
491/491 [==============================] - 1s - loss: 1.3734 - mean_squared_error: 1.3734 - val_loss: 2.3675 - val_mean_squared_error: 2.3675
Epoch 5/100
491/491 [==============================] - 1s - loss: 1.2504 - mean_squared_error: 1.2504 - val_loss: 2.1871 - val_mean_squared_error: 2.1871
Epoch 6/100
491/491 [==============================] - 1s - loss: 1.2306 - mean_squared_error: 1.2306 - val_loss: 2.2680 - val_mean_squared_error: 2.2680
Epoch 7/100
491/491 [=========

491/491 [==============================] - 1s - loss: 0.5027 - mean_squared_error: 0.5027 - val_loss: 0.8078 - val_mean_squared_error: 0.8078
Epoch 54/100
491/491 [==============================] - 1s - loss: 0.4701 - mean_squared_error: 0.4701 - val_loss: 0.8023 - val_mean_squared_error: 0.8023
Epoch 55/100
491/491 [==============================] - 1s - loss: 0.4120 - mean_squared_error: 0.4120 - val_loss: 0.8272 - val_mean_squared_error: 0.8272
Epoch 56/100
491/491 [==============================] - 1s - loss: 0.4636 - mean_squared_error: 0.4636 - val_loss: 0.8175 - val_mean_squared_error: 0.8175
Epoch 57/100
491/491 [==============================] - 1s - loss: 0.4592 - mean_squared_error: 0.4592 - val_loss: 0.8403 - val_mean_squared_error: 0.8403
Epoch 58/100
491/491 [==============================] - 1s - loss: 0.4172 - mean_squared_error: 0.4172 - val_loss: 0.8786 - val_mean_squared_error: 0.8786
Epoch 59/100
491/491 [==============================] - 1s - loss: 0.4216 - mean_sq

In [45]:
preds = model.predict(x_test)
preds = preds.reshape(preds.shape[0])

#### Prediction Eval

In [46]:
mean_y = np.mean(preds)
print("Mean of predictions is: "+str(mean_y))

mse = np.mean((y_test - preds)**2)
print("Variance (benchmark) is: "+str(mse))

Mean of predictions is: 1.65871
Variance (benchmark) is: 0.8843350405884116


In [47]:
preds

array([ 2.9370687 ,  2.86960268,  2.60364652,  2.35215139,  1.61213088,
        2.36231065,  0.92654347,  1.66885567,  0.30839017,  1.54102659,
        0.46046084,  1.17673254,  1.06782055,  1.22596359,  0.93251181,
        3.25358295,  2.78149176,  1.67381716,  1.23727059,  0.20302521,
        1.60256827,  1.88018322,  0.89881623,  2.36440444,  3.00015736,
        1.76857328,  0.66433799,  0.56920522,  1.18367529,  1.61894858,
        0.46460742,  0.45883584,  2.66710782,  2.87744474,  1.1294955 ,
        1.98543084,  2.34261322,  1.41242576,  1.03656435,  1.24692261,
        1.64408052,  1.42260742,  1.10641313,  0.56041658,  2.66080976,
        1.11443019,  3.71967149,  1.63532317,  0.92877382,  3.64372087,
        0.95324636,  2.77706099,  2.36249447,  3.59891224,  0.69960868,
        0.13275936,  1.48006153,  2.31116009,  1.35569644,  1.90782821,
        0.72599232,  3.46610141,  1.06118333,  0.64507425,  2.89716125,
        2.71648383,  3.11236882,  1.15700746,  1.85945249,  0.98

#### Benchmark Eval

In [48]:
mean_y = np.mean(y_test)
print("Mean of test set is: "+str(mean_y))

variance = np.mean((y_test - np.mean(y_test))**2)
print("Variance (benchmark) is: "+str(variance))

Mean of test set is: 1.886178861788618
Variance (benchmark) is: 1.3691585696344772


# Simple LSTM Dominance

In [49]:
WINDOW_SIZE = 25
num_feat_map = 16
feat_dim = 136

model = Sequential()

x_train, x_test, y_train, y_test = train_test_split(x, y1, test_size=0.2, random_state=42)

x_train = x_train.reshape((491,25,-1))
x_test = x_test.reshape((123,25,-1))

create_graph_arousal_dominance()

epochs = 60
batch_size=32

earlystop = EarlyStopping(monitor='val_loss', min_delta=0, patience=10, verbose=1, mode='auto')
sgd = keras.optimizers.SGD(lr=0.01, clipnorm=1.)
filepath="weights_best_arousal.hdf5"
checkpoint = ModelCheckpoint(filepath, monitor='val_loss', verbose=1, save_best_only=True, mode='min')

#adam1 = keras.optimizers.Adam(lr=0.0001, beta_1=0.9, beta_2=0.999, epsilon=1e-08, decay=0.0)

model.compile(loss=keras.losses.mean_squared_error,
              optimizer='adam',
              metrics=['mse'])

model.fit(x_train, y_train,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1,
          shuffle=True,
          validation_data=(x_test, y_test))

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
batch_normalization_13 (Batc (None, 25, 136)           544       
_________________________________________________________________
lstm_13 (LSTM)               (None, 25, 16)            9792      
_________________________________________________________________
batch_normalization_14 (Batc (None, 25, 16)            64        
_________________________________________________________________
lstm_14 (LSTM)               (None, 16)                2112      
_________________________________________________________________
dropout_7 (Dropout)          (None, 16)                0         
_________________________________________________________________
dense_7 (Dense)              (None, 1)                 17        
Total params: 12,529
Trainable params: 12,225
Non-trainable params: 304
_________________________________________________________________
Trai

491/491 [==============================] - 1s - loss: 0.6613 - mean_squared_error: 0.6613 - val_loss: 0.6359 - val_mean_squared_error: 0.6359
Epoch 47/60
491/491 [==============================] - 1s - loss: 0.7964 - mean_squared_error: 0.7964 - val_loss: 0.7720 - val_mean_squared_error: 0.7720
Epoch 48/60
491/491 [==============================] - 1s - loss: 0.7058 - mean_squared_error: 0.7058 - val_loss: 0.6729 - val_mean_squared_error: 0.6729
Epoch 49/60
491/491 [==============================] - 1s - loss: 0.6759 - mean_squared_error: 0.6759 - val_loss: 0.6822 - val_mean_squared_error: 0.6822
Epoch 50/60
491/491 [==============================] - 1s - loss: 0.7038 - mean_squared_error: 0.7038 - val_loss: 0.6121 - val_mean_squared_error: 0.6121
Epoch 51/60
491/491 [==============================] - 1s - loss: 0.7673 - mean_squared_error: 0.7673 - val_loss: 0.6363 - val_mean_squared_error: 0.6363
Epoch 52/60
491/491 [==============================] - 1s - loss: 0.6650 - mean_squared_

#### Eval

In [50]:
preds = model.predict(x_test)
preds = preds.reshape(preds.shape[0])

mean_y = np.mean(preds)
print("Mean of predictions is: "+str(mean_y))

mse = np.mean((y_test - preds)**2)
print("Variance (benchmark) is: "+str(mse))

print()

mean_y = np.mean(y_test)
print("Mean of test set is: "+str(mean_y))

variance = np.mean((y_test - np.mean(y_test))**2)
print("Variance (benchmark) is: "+str(variance))

Mean of predictions is: 2.20046
Variance (benchmark) is: 0.6669065394550879

Mean of test set is: 2.3983739837398375
Variance (benchmark) is: 0.7437371934694955


In [51]:
preds

array([ 1.93438828,  2.85008526,  2.94865203,  1.59903073,  1.92163181,
        1.71720862,  2.96405625,  1.63232052,  1.90440106,  2.65493441,
        2.2405498 ,  0.28412151,  2.09852314,  2.85752106,  1.92819703,
        1.77414715,  2.78698397,  2.83201766,  2.32855535,  2.18887043,
        1.96209598,  2.00622106,  1.44849026,  2.62282562,  1.9600687 ,
        2.45689845,  1.20643401,  2.1491313 ,  2.74603939,  2.12131214,
        1.12179673,  2.08844233,  2.61769485,  2.35749626,  1.85754907,
        2.52867079,  1.97575128,  1.71261132,  1.4023807 ,  2.16627312,
        2.86901736,  1.35656846,  2.98326397,  1.76708508,  2.38357306,
        2.33252597,  3.09941125,  2.37027478,  2.36272693,  2.99411798,
        1.79808366,  2.76097298,  1.57374728,  2.54396415,  2.11508846,
        1.89099157,  2.40068293,  2.33851147,  2.17876196,  2.42810583,
        2.21405435,  2.91950178,  1.36441004,  2.4013412 ,  2.83751059,
        2.36942887,  2.07267213,  2.10179186,  1.95358908,  1.43

# Simple LSTM Model Emotions

In [77]:
def create_graph_emotions():
    
    model.add(BatchNormalization(input_shape=(WINDOW_SIZE,feat_dim)))
    model.add(LSTM(num_feat_map, 
                   return_sequences=True))
    model.add(BatchNormalization())
    model.add(LSTM(num_feat_map, return_sequences=False))
    model.add(Dropout(0.5))
    model.add(Dense(4,activation='softmax'))
    
    model.summary()

In [78]:
WINDOW_SIZE = 25
num_feat_map = 16
feat_dim = 136

model = Sequential()

label_encoder = LabelEncoder()
y2 = label_encoder.fit_transform(y2)

x_train, x_test, y_train, y_test = train_test_split(x, y2, test_size=0.2, random_state=42)

x_train = x_train.reshape((491,25,-1))
x_test = x_test.reshape((123,25,-1))

y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

create_graph_emotions()

epochs = 100
batch_size=32

#earlystop = EarlyStopping(monitor='val_loss', min_delta=0, patience=10, verbose=1, mode='auto')
#filepath="weights_best_arousal.hdf5"
#checkpoint = ModelCheckpoint(filepath, monitor='val_loss', verbose=1, save_best_only=True, mode='min')


model.compile(loss=keras.losses.mean_squared_error,
              optimizer='adam',
              metrics=['accuracy'])

model.fit(x_train, y_train,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1,
          shuffle=True,
          validation_data=(x_test, y_test))

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
batch_normalization_21 (Batc (None, 25, 136)           544       
_________________________________________________________________
lstm_21 (LSTM)               (None, 25, 16)            9792      
_________________________________________________________________
batch_normalization_22 (Batc (None, 25, 16)            64        
_________________________________________________________________
lstm_22 (LSTM)               (None, 16)                2112      
_________________________________________________________________
dropout_11 (Dropout)         (None, 16)                0         
_________________________________________________________________
dense_11 (Dense)             (None, 4)                 68        
Total params: 12,580
Trainable params: 12,276
Non-trainable params: 304
_________________________________________________________________
Trai

491/491 [==============================] - 1s - loss: 0.0956 - acc: 0.7373 - val_loss: 0.1590 - val_acc: 0.5203
Epoch 58/100
491/491 [==============================] - 1s - loss: 0.0939 - acc: 0.7637 - val_loss: 0.1579 - val_acc: 0.5122
Epoch 59/100
491/491 [==============================] - 1s - loss: 0.0974 - acc: 0.7169 - val_loss: 0.1662 - val_acc: 0.5122
Epoch 60/100
491/491 [==============================] - 1s - loss: 0.0934 - acc: 0.7556 - val_loss: 0.1673 - val_acc: 0.5041
Epoch 61/100
491/491 [==============================] - 1s - loss: 0.0972 - acc: 0.7251 - val_loss: 0.1669 - val_acc: 0.5447
Epoch 62/100
491/491 [==============================] - 1s - loss: 0.0952 - acc: 0.7413 - val_loss: 0.1623 - val_acc: 0.5447
Epoch 63/100
491/491 [==============================] - 1s - loss: 0.0861 - acc: 0.7760 - val_loss: 0.1655 - val_acc: 0.5203
Epoch 64/100
491/491 [==============================] - 1s - loss: 0.0885 - acc: 0.7699 - val_loss: 0.1656 - val_acc: 0.5366
Epoch 65/100


#### Eval

In [79]:
preds = model.predict_classes(x_test)
preds

123/123 [==============================] - 0s     


array([2, 3, 2, 2, 2, 2, 0, 3, 0, 3, 0, 2, 0, 0, 2, 3, 2, 2, 0, 0, 2, 2, 1,
       3, 2, 0, 2, 2, 3, 2, 3, 1, 3, 2, 1, 2, 2, 2, 3, 2, 0, 2, 2, 2, 1, 2,
       3, 2, 2, 2, 2, 2, 1, 2, 0, 0, 3, 2, 2, 2, 1, 3, 2, 0, 3, 2, 3, 2, 2,
       0, 1, 3, 0, 0, 3, 3, 2, 1, 0, 1, 3, 2, 2, 2, 3, 3, 2, 2, 3, 1, 1, 3,
       2, 2, 2, 2, 2, 2, 0, 0, 3, 0, 2, 0, 2, 2, 2, 1, 2, 2, 3, 1, 2, 3, 2,
       3, 1, 0, 0, 3, 3, 2, 3], dtype=int64)

In [80]:
y_test = np.argmax(y_test,axis=1)
y_test

array([1, 3, 2, 2, 1, 2, 2, 2, 0, 2, 0, 2, 0, 0, 1, 3, 2, 2, 0, 3, 2, 0, 0,
       3, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 0, 2, 1, 0, 3, 0, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 0, 2, 0, 0, 0, 2, 2, 3, 1, 0, 2, 3, 3, 1, 2, 3, 2,
       0, 1, 3, 0, 2, 2, 2, 2, 0, 2, 0, 3, 0, 0, 2, 2, 3, 2, 2, 3, 1, 0, 3,
       0, 0, 0, 1, 1, 0, 2, 0, 3, 2, 2, 0, 2, 2, 3, 0, 2, 0, 2, 1, 2, 2, 1,
       2, 1, 2, 2, 3, 2, 2, 2], dtype=int64)

In [83]:
confusion_matrix(y_test,preds)

array([[11,  7, 10,  2],
       [ 0,  6,  8,  1],
       [ 9,  1, 37, 14],
       [ 2,  0,  3, 12]], dtype=int64)

In [86]:
print(classification_report(y_test,preds))

             precision    recall  f1-score   support

          0       0.50      0.37      0.42        30
          1       0.43      0.40      0.41        15
          2       0.64      0.61      0.62        61
          3       0.41      0.71      0.52        17

avg / total       0.55      0.54      0.53       123

